# Generated by Django 4.0 on 2022-01-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmcsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('query', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
