# Generated by Django 4.0 on 2022-01-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmcsite', '0002_query_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('event_img', models.FileField(upload_to='')),
            ],
        ),
    ]
