# Generated by Django 4.0 on 2022-01-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmcsite', '0003_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='event_img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
