# Generated by Django 4.0 on 2022-01-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmcsite', '0004_alter_gallery_event_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('experience', models.TextField()),
            ],
        ),
    ]
