# Generated by Django 4.0 on 2022-01-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmcsite', '0006_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(height_field='300', upload_to='media', width_field='300'),
        ),
    ]
